name: test

on:
  push:
    branches:
      - dev

jobs:
  dev_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: setup cmake
        uses: jwlawson/actions-setup-cmake@v1.4
        with:
          cmake-version: '3.17.x'

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: test
        working-directory: build
        run: ./test

      - name: run-app
        working-directory: build
        run: ./app -i ../instances/sample.txt -s PIBT -o result.txt -v
